### ISSUE TITLE
TS7006: Parameter 'event' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by gotnull** [fegyi001/mangol#10]
I set `"noImplicitAny": true` in my `tsconfig.json` to enforce type declarations.

Line 45 of `node_modules/mangol/src/lib/modules/print/print.component.ts`

> Error: TS7006: Parameter 'event' implicitly has an 'any' type.

`map.once('postcompose', function (event)`

Should be:

`map.once('postcompose', function (event: any)`

**Comment by fegyi001** [comment]
Thanks for the remark, it is fixed now in version 0.3.16

**Comment by vishambardutt** [comment]
i put function in app.component.ts file
 myEvent(evt){
    console.log(evt );
  }
and  call this function in 
app.component.html
<button (click)="myEvents('This is click event')">CLICK ME</button>
showing error: src/app/app.component.ts:16:10 - error TS7006: Parameter 'evt' implicitly has an 'any' type.

I set "noImplicitAny": true in my tsconfig.json to enforce type declarations. yet not working 

kindly help me

**Comment by VishnuVardhanReddy96** [comment]
Thanks
