### ISSUE TITLE
Dynamic layer visibility

### ISSUE THREAD

**Issue by ramiro87** [fegyi001/mangol#13]
Hi, this is not a problem, I would like to know some way to dynamically display in console the visibility of  the layers. Thanks for the answer.

**Comment by fegyi001** [comment]
If you add an event listener to the mapReady output parameter of <mangol>, you can do anything you want with the MangolMap object(s) which inherit all the properties & methods of the ol.Map object such as getLayers(). Here I simply console.log all the layers and their opacities.

```typescript
@Component({
  selector: 'my-app',
  template: `
      <mangol (mapReady)="onMapReady($event)"></mangol>
    `
})
export class DemoFullComponent implements OnInit {

  mapService: MangolMapService;

  onMapReady($event: { mapService: MangolMapService }) {
    this.mapService = $event.mapService;
    const map = this.mapService.getMaps()[0];
    map.getLayers().forEach(l => {
      console.log(l);
      console.log('opacity: ' + l.getOpacity());
    });

  }
}
```
