### ISSUE TITLE
+1 for measurements

### ISSUE THREAD

**Issue by AndreasSchmid1** [fegyi001/mangol#15]
Thank you for that great repo. Would love to see basic measurements like rectangle or lines

**Comment by fegyi001** [comment]
I'll try my best. I have very limited time developing this project. But measurements is on top of my to-do list. Thanks for the request!

**Comment by fegyi001** [comment]
@AndreasSchmid1 I recently implemented measuring. Check version 0.7.0 or the live demo. At the moment line and area measurements are possible.

**Comment by fegyi001** [comment]
@AndreasSchmid1 you may close this feature request if you think the implementation satisfies your needs.
