### ISSUE TITLE
How can i change the height of the map？

### ISSUE THREAD

**Issue by cumtfc** [fegyi001/mangol#16]
It is too short for me. I tried the npm version,the height is changed by the window size ,but i need to do some changes.

**Comment by jcendal** [comment]
i dont's understand you. For changing the height yo can see the tutorial in https://www.npmjs.com/package/mangol

**Comment by cumtfc** [comment]
Thanks, and I found my solution by packaging it by myself,referring to this project.
Thanks a lot.
