### ISSUE TITLE
Which version of Mangol moved to Angular5?

### ISSUE THREAD

**Issue by pmeems** [fegyi001/mangol#19]
We're facing all kind of strange errors after upgrading from Mangol v0.3.6 to v0.7.9.

I suspect it is because our application needs to stay in Angular4 and Mangol moved to Angular5.

Which version of Mangol moved to Angular5? So we can get its previous version?

**Comment by Ricommander** [comment]
Its version 0.5.0. 
So the last version using Angular4 is 0.4.3.

**Comment by fegyi001** [comment]
Why do you stick to Angular4?

**Comment by fegyi001** [comment]
By the way, I completely refactored the project, please try the latest version (1.0.0 now), hopefully the errors will disappear.

**Comment by Ricommander** [comment]
Thanks for the new version.

It was too much effort to convert the project to angular 5. In addition some other dependencies are still not fit for angular 5 and produce errors during compilation.
