### ISSUE TITLE
How to use aol-source-tilewms

### ISSUE THREAD

**Issue by SemVC7** [fegyi001/mangol#2]
Can you please provide me an example of the <aol-source-tilewms> implementation? 

Thanks in advance!

**Comment by fegyi001** [comment]
What do you mean by 'aol-source-tilewms'? Maybe ol.source.TileWMS? Your question is not Mangol specific. You simply have to create an ol.layer.Tile object with an ol.source.TileWMS source as a property, and add it as a layer to the config. Just check the 'src/app/demos/demo-layertree.ts' file, you can see a working example there.
