### ISSUE TITLE
implementation example doesn't work as described. Error: ng_dev variable in node modules missing

### ISSUE THREAD

**Issue by mshakhomirov** [fegyi001/mangol#21]

**Comment by fegyi001** [comment]
Thanks for the feedback! It seems that there was an issue with typescript 2.6.2. I had to fall back to 2.5.3 and now everything should work as expected. Please let me know how it worked for you with the new version (1.0.9). Thanks!

**Comment by mshakhomirov** [comment]
Works now. Thank you very much for your quick response, Gergely.
