### ISSUE TITLE
Error: Unexpected value 'MangolModule' imported by the module

### ISSUE THREAD

**Issue by gotnull** [fegyi001/mangol#23]
```Error: Unexpected value 'MangolModule' imported by the module 'MapModule'. Please add a @NgModule annotation.```

**Comment by fegyi001** [comment]
@gotnull  I just published a fresh version of Mangol which is completely rewritten for Angular6+. Please check whether it solves your problem. 
But the API has changed a bit, please visit the github main Readme to see how MangolConfig should be configured from now on.
