### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by Cosmocat** [fegyi001/mangol#24]
Fullscreen mode does not have same layers settings (on/off, opacity settings) as it's 'parent' component and vice versa. It would have been nice to keep state between those modes intact.

Thank you anyway for this great project.

**Comment by fegyi001** [comment]
@Cosmocat I've completely rewritten Mangol for Angular6, and the fullscreen button works quite differently from now on, using the Fullscreen API. Now the same map becomes full-screen.
