### ISSUE TITLE
"export 'f' was not found in 'ol/format/filter'

### ISSUE THREAD

**Issue by happyMeow** [fegyi001/mangol#27]
Hello,When I use the 'ol.format.filter' to get spatial query,I got an error:"export 'default' (imported as 'filter2') was not found in 'ol/format/filter',has anyone got this error too?

**Comment by fegyi001** [comment]
Could you give a little code example where the error comes?

**Comment by fegyi001** [comment]
By the way, this seems nothing to do with Mangol. This seems to be an OL issue.
