### ISSUE TITLE
Multiple instances of mangol

### ISSUE THREAD

**Issue by Cosmocat** [fegyi001/mangol#28]
Hi, in previous versions I was definitely able to create multiple instances of mangol on same page. It seems like you can't do it anymore in recent version. Is that correct?

**Comment by fegyi001** [comment]
I don't really get it. There is no new version of Mangol yet on npm, only the source code was modified (updated to Angular8). What do you mean by 'recent version'?

**Comment by fegyi001** [comment]
But I'm surprised that you could create multiple instances of Mangol before. Mangol was not designed for that. This can be done, however, although it requires quite big modifications everywhere in the code.

**Comment by fegyi001** [comment]
Well, now there is a new version out (8.1.3, following its Angular version). But, as I said, Mangol was not designed to support multiple instances.

**Comment by Cosmocat** [comment]
Thanks, I'm pretty sure I was able to do it in v. 1.0.10 by creating <mangol> components with unique id. Thanks for a clarification anyway!
