### ISSUE TITLE
How to use map.getView() with example config?

### ISSUE THREAD

**Issue by ghost** [fegyi001/mangol#4]
Hi!

this.config.map.getView() returns "it's not a function".

How to access getView() from config object to center the map after initialization. 
E.g. center and zoom after markers have loaded.

Thanks!

**Comment by fegyi001** [comment]
The config you mention is only a JavaScript object that gets parsed by Mangol. This does not return anything, but you can listen to the mangol component's onMapReady() event which gives back a MangolMapService object which contains the map(s) that were initialized. 

Check the main Readme.md's "More hooks" section, you can see an example how simple it is. 

This is your template: 
`<mangol (mapReady)="onMapReady($event)"></mangol>`

And in your exported class, do it like this:
`onMapReady($event: any) {
// you can obtain the MangolMapService instance here
    const mapService: MangolMapService = $event.mapService;
// you can obtain your map(s) from the MangolMapService
    const map: MangolMap = mapService.getMaps()[0];
// with the map you can get its ol.View and go on...
    console.log(map.getView().getCenter());
  }
`

**Comment by ghost** [comment]
@fegyi001 
Thank you for explaining!
Everything works now.
