### ISSUE TITLE
Problem with the map displayed

### ISSUE THREAD

**Issue by jcendal** [fegyi001/mangol#7]
Hello! 

When I try to represent the map with "[config]" in the mangol tag all the "sidebar" options are displayed but the map is not displayed and sends this error "ExpressionChangedAfterItHasBeenCheckedError". I adjunt a photo.

![1](https://user-images.githubusercontent.com/29627990/28321255-1633f98a-6bd3-11e7-8615-0d0de6c23447.png)
![2](https://user-images.githubusercontent.com/29627990/28321257-163dadd6-6bd3-11e7-9ba9-bf99c31836b9.png)
![3](https://user-images.githubusercontent.com/29627990/28321256-163450d8-6bd3-11e7-8059-e8fc55dd8dbf.png)

**Comment by fegyi001** [comment]
This is a common issue with Angular when you are not in prod mode. I recommend using 
enableProdMode() in your main.ts
```typescript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

enableProdMode();

platformBrowserDynamic().bootstrapModule(AppModule);

```

**Comment by jcendal** [comment]
Yes, the lifecycle error say goodbye, my true error is this.

ERROR TypeError: Cannot read property 'G' of null                core.es5.js:1020 
    at zc (ol.js:42)
    at rw (ol.js:745)
    at vw (ol.js:750)
    at ww (ol.js:752)
    at Nw.k.Nc (ol.js:751)
    at Vv.sd (ol.js:721)
    at hi.Jg (ol.js:174)
    at MangolMap.k.Sp (ol.js:293)
    at MangolMap.<anonymous> (ol.js:279)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)

**Comment by fegyi001** [comment]
I can't reproduce your error. However, I upgraded Mangol to v0.3.10, please use this version. Take care, that when import as a module you no longer should do it like this: MangolModule.forRoot(), but instead simply MangolModule.

**Comment by fegyi001** [comment]
Could you paste here the full content of your dashboard.component.ts file? That would help.

**Comment by jcendal** [comment]
The full code of dashboard.component.ts:

import {Component, OnInit} from '@angular/core';
import { routerTransition } from '../../router.animations';

import * as ol from 'openlayers'

@Component({
    selector: 'app-dashboard',
    templateUrl: 'dashboard.component.html',
    styleUrls: ['./dashboard.component.scss'],
    animations: [routerTransition()]
})
export class DashboardComponent implements OnInit {
    config: any;
    public ngOnInit() {
        this.config = {
            map: {
                renderer: 'canvas',
                target: 'demo-layertree',
                view: {
                    projection: 'EPSG:900913',
                    center: ol.proj.fromLonLat([0, 0], 'EPSG:900913'),
                    zoom: 7
                },
                layers: [
                    {
                        type: 'layergroup',
                        name: 'Base layers',
                        expanded: false,
                        visible: true,
                        children: [
                            {
                                type: 'layer',
                                name: 'OpenStreetMap layer',
                                visible: false,
                                opacity: 1,
                                layer: new ol.layer.Tile({
                                    source: new ol.source.OSM()
                                })
                            }
                        ]
                    }, {
                        type: 'layergroup',
                        name: 'Hungary',
                        expanded: false,
                        visible: true,
                        children: [
                            {
                                type: 'layer',
                                name: 'Main roads',
                                visible: false,
                                opacity: 1.0,
                                layer: new ol.layer.Tile({
                                    source: new ol.source.TileWMS({
                                        url: 'http://188.166.116.137:8081/geoserver/wms',
                                        params: {
                                            LAYERS: 'osmWsp:trunk_primary',
                                            SRS: 'EPSG:900913',
                                            FORMAT: 'image/png',
                                            TILED: true
                                        },
                                        serverType: 'geoserver',
                                        projection: 'EPSG:900913'
                                    })
                                })
                            }, {
                                type: 'layer',
                                name: 'Highways',
                                visible: false,
                                opacity: 1.0,
                                layer: new ol.layer.Tile({
                                    source: new ol.source.TileWMS({
                                        url: 'http://188.166.116.137:8081/geoserver/wms',
                                        params: {
                                            LAYERS: 'osmWsp:motorway',
                                            SRS: 'EPSG:900913',
                                            FORMAT: 'image/png',
                                            TILED: true
                                        },
                                        serverType: 'geoserver',
                                        projection: 'EPSG:900913'
                                    })
                                })
                            },
                            {
                                type: 'layer',
                                name: 'Country border',
                                visible: false,
                                opacity: 1.0,
                                layer: new ol.layer.Tile({
                                    source: new ol.source.TileWMS({
                                        url: 'http://188.166.116.137:8081/geoserver/wms',
                                        params: {
                                            LAYERS: 'osmWsp:country',
                                            SRS: 'EPSG:900913',
                                            FORMAT: 'image/png',
                                            TILED: true
                                        },
                                        serverType: 'geoserver',
                                        projection: 'EPSG:900913'
                                    })
                                })
                            }
                        ]
                    }
                ]
            },
            sidebar: {
                collapsible: true,
                opened: true,
                toolbar: {
                    layertree: {}
                }
            }
        };
    }

}

**Comment by jcendal** [comment]
The full code of dashboard.component.ts file:
```import {Component, OnInit} from '@angular/core';
import { routerTransition } from '../../router.animations';

import * as ol from 'openlayers'

@Component({
    selector: 'app-dashboard',
    templateUrl: 'dashboard.component.html',
    styleUrls: ['./dashboard.component.scss'],
    animations: [routerTransition()]
})
export class DashboardComponent implements OnInit {
    config: any;
    public ngOnInit() {
        this.config = {
            map: {
                renderer: 'canvas',
                target: 'demo-layertree',
                view: {
                    projection: 'EPSG:900913',
                    center: ol.proj.fromLonLat([0, 0], 'EPSG:900913'),
                    zoom: 7
                },
                layers: [
                    {
                        type: 'layergroup',
                        name: 'Base layers',
                        expanded: false,
                        visible: true,
                        children: [
                            {
                                type: 'layer',
                                name: 'OpenStreetMap layer',
                                visible: false,
                                opacity: 1,
                                layer: new ol.layer.Tile({
                                    source: new ol.source.OSM()
                                })
                            }
                        ]
                    }, {
                        type: 'layergroup',
                        name: 'Hungary',
                        expanded: false,
                        visible: true,
                        children: [
                            {
                                type: 'layer',
                                name: 'Main roads',
                                visible: false,
                                opacity: 1.0,
                                layer: new ol.layer.Tile({
                                    source: new ol.source.TileWMS({
                                        url: 'http://188.166.116.137:8081/geoserver/wms',
                                        params: {
                                            LAYERS: 'osmWsp:trunk_primary',
                                            SRS: 'EPSG:900913',
                                            FORMAT: 'image/png',
                                            TILED: true
                                        },
                                        serverType: 'geoserver',
                                        projection: 'EPSG:900913'
                                    })
                                })
                            }, {
                                type: 'layer',
                                name: 'Highways',
                                visible: false,
                                opacity: 1.0,
                                layer: new ol.layer.Tile({
                                    source: new ol.source.TileWMS({
                                        url: 'http://188.166.116.137:8081/geoserver/wms',
                                        params: {
                                            LAYERS: 'osmWsp:motorway',
                                            SRS: 'EPSG:900913',
                                            FORMAT: 'image/png',
                                            TILED: true
                                        },
                                        serverType: 'geoserver',
                                        projection: 'EPSG:900913'
                                    })
                                })
                            },
                            {
                                type: 'layer',
                                name: 'Country border',
                                visible: false,
                                opacity: 1.0,
                                layer: new ol.layer.Tile({
                                    source: new ol.source.TileWMS({
                                        url: 'http://188.166.116.137:8081/geoserver/wms',
                                        params: {
                                            LAYERS: 'osmWsp:country',
                                            SRS: 'EPSG:900913',
                                            FORMAT: 'image/png',
                                            TILED: true
                                        },
                                        serverType: 'geoserver',
                                        projection: 'EPSG:900913'
                                    })
                                })
                            }
                        ]
                    }
                ]
            },
            sidebar: {
                collapsible: true,
                opened: true,
                toolbar: {
                    layertree: {}
                }
            }
        };
    }

}

```

**Comment by jcendal** [comment]
With the new version of Mangol all work right!!! Thanks you for the update 👍 👍 

![1](https://user-images.githubusercontent.com/29627990/28441543-9853e34c-6dab-11e7-86b7-f760e907b73a.png)

**Comment by fegyi001** [comment]
Glad to hear that!
