### ISSUE TITLE
Error encountered resolving symbol values statically. Function calls are not supported.

### ISSUE THREAD

**Issue by cse-t-kutsuna** [fegyi001/mangol#8]
Hello.

I tried to use mangol with @angular/cli@1.2.1, but it got the following error.

```
ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /Users/me/git/study/blah-map/node_modules/mangol/node_modules/@angular/core/core.d.ts, resolving symbol MangolRootModule in /Users/me/git/study/blah-map/node_modules/mangol/src/lib/modules/_index.ts, resolving symbol MangolRootModule in /Users/me/git/study/blah-map/node_modules/mangol/src/lib/modules/_index.ts
webpack: Failed to compile.
```

**Comment by fegyi001** [comment]
I recently upgraded to the latest Angular version (4.3.0) and also the angular-cli version (1.2.1). Try it out with Mangol v.0.3.8 !

**Comment by fegyi001** [comment]
I made another upgrade by removing the forRoot() invocation of MangolModule. Now it must work properly.

**Comment by cse-t-kutsuna** [comment]
Thank you for your prompt reply! ^^

**Comment by cse-t-kutsuna** [comment]
@fegyi001 But, I got the same error.
Angular 4.3.1
angular-cli 1.2.1
Mangol 0.3.10

sorry updated.

**Comment by fegyi001** [comment]
Try update with an even newer version of Mangol (0.3.10). 
Then you should not get that error, since MangolRootModule is not in Mangol anymore. But take care, don't import MangolModule as before (MangolModule.forRoot()), but only as MangolModule.

I don't know which typescript version you use, I recommend 2.3.3

**Comment by cse-t-kutsuna** [comment]
I tried both typescript 2.3.4 and 2.3.3.

Is something wrong?
https://github.com/cse-t-kutsuna/blah-map/tree/feature/add_mangol

**Comment by fegyi001** [comment]
[blahmap.zip](https://github.com/fegyi001/mangol/files/1161972/blahmap.zip)

I upgraded Mangol to v0.3.13, which now uses Angular v4.3.1 (until now it used v4.3.0). Your project used 4.0.0 (generated by default with angular-cli). I modified your project, see the attached zip file.

Here is a screenshot of the working app:
![000](https://user-images.githubusercontent.com/4125222/28413666-bbed37ee-6d48-11e7-88b7-98c22144bdee.png)

**Comment by fegyi001** [comment]
Ah, and I also strongly recommend to delete the whole node_modules folder and install freshly all dependencies.

**Comment by jcendal** [comment]
1-Delete your node_module, 2-Use this code:

```
npm i -g npm-check-updates
npm-check-updates -u
npm install
```

I solved my similar error with this metod

**Comment by cse-t-kutsuna** [comment]
@fegyi001 When updating to 0.3.13 the error disappeared.
Thank you!

**Comment by fegyi001** [comment]
Glad to hear that!
